<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PengaduanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pengaduan')->insert([
            [
                'kode_pengaduan' => 'PGD-001',
                'judul' => 'Air keruh di rumah warga',
                'deskripsi' => 'Air berwarna coklat dan berbau',
                'lokasi' => 'Jl. Raya Darmo No. 88, Wonokromo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-002',
                'judul' => 'Kebocoran pipa utama',
                'deskripsi' => 'Air keluar dari pipa distribusi utama',
                'lokasi' => 'Jl. Manyar Kertoarjo No. 12, Gubeng, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-003',
                'judul' => 'Meter air tidak berjalan',
                'deskripsi' => 'Meter tidak mencatat pemakaian air',
                'lokasi' => 'Jl. HR Muhammad No. 45, Sukomanunggal, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-004',
                'judul' => 'Tekanan air kecil',
                'deskripsi' => 'Debit air sangat kecil pada pagi hari',
                'lokasi' => 'Jl. Ahmad Yani No. 120, Wonocolo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-005',
                'judul' => 'Air tidak keluar',
                'deskripsi' => 'Tidak ada suplai air sejak pagi',
                'lokasi' => 'Jl. Tunjungan No. 10, Genteng, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-006',
                'judul' => 'Pipa bocor di gang perumahan',
                'deskripsi' => 'Terjadi rembesan air di area jalan gang',
                'lokasi' => 'Jl. Dharmahusada Indah Timur No. 17, Mulyorejo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-007',
                'judul' => 'Tagihan tidak sesuai pemakaian',
                'deskripsi' => 'Tagihan air meningkat drastis bulan ini',
                'lokasi' => 'Jl. Ketintang Baru Selatan No. 22, Gayungan, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-008',
                'judul' => 'Meter air rusak',
                'deskripsi' => 'Meter pecah dan tidak dapat dibaca',
                'lokasi' => 'Jl. Kapas Krampung No. 50, Tambaksari, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-009',
                'judul' => 'Air berbau kaporit berlebihan',
                'deskripsi' => 'Air memiliki bau kimia menyengat',
                'lokasi' => 'Jl. Rungkut Madya No. 30, Rungkut, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-010',
                'judul' => 'Saluran air tersumbat',
                'deskripsi' => 'Aliran air tidak lancar dan sering mati',
                'lokasi' => 'Jl. Dukuh Kupang Barat No. 19, Dukuh Pakis, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-011',
                'judul' => 'Saluran air bocor',
                'deskripsi' => 'Aliran air tidak lancar dan sering mati karena bocor',
                'lokasi' => 'Kecipik, Boteng, Menganti, Gresik Regency',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-012',
                'judul' => 'Kualitas air keruh di kawasan kampus',
                'deskripsi' => 'Air berwarna kekuningan dan meninggalkan endapan.',
                'lokasi' => 'Telkom University Surabaya, Jl. Ketintang No. 156, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(11),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-013',
                'judul' => 'Kebocoran instalasi pipa kantor',
                'deskripsi' => 'Terdapat kebocoran pada pipa distribusi internal.',
                'lokasi' => 'PDAM Surya Sembada Kota Surabaya, Jl. Prof. Dr. Moestopo No. 2, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-014',
                'judul' => 'Tekanan air rendah pada jam sibuk',
                'deskripsi' => 'Tekanan air menurun drastis pada pagi dan sore hari.',
                'lokasi' => 'Jl. Merr Kalijudan No. 75, Mulyorejo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(13),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-015',
                'judul' => 'Pipa distribusi pecah',
                'deskripsi' => 'Pipa utama pecah sehingga air menggenangi jalan.',
                'lokasi' => 'Jl. Raya Kendangsari No. 23, Tenggilis Mejoyo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(14),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-016',
                'judul' => 'Meter air macet',
                'deskripsi' => 'Meter tidak bergerak meskipun air digunakan.',
                'lokasi' => 'Jl. Semolowaru Elok No. 11, Sukolilo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-017',
                'judul' => 'Air mati total selama dua hari',
                'deskripsi' => 'Tidak ada suplai air ke rumah warga sejak dua hari lalu.',
                'lokasi' => 'Jl. Ngagel Jaya Selatan No. 56, Gubeng, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-018',
                'judul' => 'Air berbau tidak sedap',
                'deskripsi' => 'Air memiliki bau menyerupai lumpur dan tidak layak digunakan.',
                'lokasi' => 'Jl. Pakuwon Indah Boulevard No. 8, Lakarsantri, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(17),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-019',
                'judul' => 'Rembesan air di trotoar',
                'deskripsi' => 'Diduga terjadi kebocoran pipa bawah tanah.',
                'lokasi' => 'Jl. Jemursari No. 120, Wonocolo, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(18),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_pengaduan' => 'PGD-020',
                'judul' => 'Tagihan air tidak wajar',
                'deskripsi' => 'Tagihan bulan ini meningkat signifikan tanpa perubahan pemakaian.',
                'lokasi' => 'Jl. Babatan Pantai Barat No. 33, Wiyung, Surabaya',
                'status' => 'Pending',
                'tanggal_pengaduan' => Carbon::now()->subDays(19),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

}
